[2024-04-03T17:55:34.261+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Chuksfx_ETL.Load_to_postgres scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-03T17:55:34.279+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Chuksfx_ETL.Load_to_postgres scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-03T17:55:34.281+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 0
[2024-04-03T17:55:34.301+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): Load_to_postgres> on 2024-04-02 00:00:00+00:00
[2024-04-03T17:55:34.310+0000] {standard_task_runner.py:60} INFO - Started process 4457 to run task
[2024-04-03T17:55:34.313+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Chuksfx_ETL', 'Load_to_postgres', 'scheduled__2024-04-02T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/include/fx_dag.py', '--cfg-path', '/tmp/tmp8ay8zfu5']
[2024-04-03T17:55:34.314+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask Load_to_postgres
[2024-04-03T17:55:34.362+0000] {task_command.py:423} INFO - Running <TaskInstance: Chuksfx_ETL.Load_to_postgres scheduled__2024-04-02T00:00:00+00:00 [running]> on host 506fa6827c3e
[2024-04-03T17:55:34.442+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Chuks' AIRFLOW_CTX_DAG_ID='Chuksfx_ETL' AIRFLOW_CTX_TASK_ID='Load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T00:00:00+00:00'
[2024-04-03T17:55:34.444+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: load_data() missing 1 required positional argument: 'df2'
[2024-04-03T17:55:34.453+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Chuksfx_ETL, task_id=Load_to_postgres, execution_date=20240402T000000, start_date=20240403T175534, end_date=20240403T175534
[2024-04-03T17:55:34.466+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task Load_to_postgres (load_data() missing 1 required positional argument: 'df2'; 4457)
[2024-04-03T17:55:34.486+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-03T18:00:40.731+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Chuksfx_ETL.Load_to_postgres scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-03T18:00:40.740+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Chuksfx_ETL.Load_to_postgres scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-03T18:00:40.741+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 0
[2024-04-03T18:00:40.755+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): Load_to_postgres> on 2024-04-02 00:00:00+00:00
[2024-04-03T18:00:40.762+0000] {standard_task_runner.py:60} INFO - Started process 4546 to run task
[2024-04-03T18:00:40.766+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Chuksfx_ETL', 'Load_to_postgres', 'scheduled__2024-04-02T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/include/fx_dag.py', '--cfg-path', '/tmp/tmp4o1ioq06']
[2024-04-03T18:00:40.768+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask Load_to_postgres
[2024-04-03T18:00:40.826+0000] {task_command.py:423} INFO - Running <TaskInstance: Chuksfx_ETL.Load_to_postgres scheduled__2024-04-02T00:00:00+00:00 [running]> on host 506fa6827c3e
[2024-04-03T18:00:40.901+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Chuks' AIRFLOW_CTX_DAG_ID='Chuksfx_ETL' AIRFLOW_CTX_TASK_ID='Load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T00:00:00+00:00'
[2024-04-03T18:00:40.998+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-03T18:00:41.007+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=Chuksfx_ETL, task_id=Load_to_postgres, execution_date=20240402T000000, start_date=20240403T180040, end_date=20240403T180041
[2024-04-03T18:00:41.059+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
